import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';

import {enabledGroups} from './site.config.mjs';

function referenceItems(dir: string) {
	const path = resolve('docs', dir, 'reference', 'sidebar.ts');

	if (!existsSync(path)) {
		return [];
	}

	// Docusaurus loads this file through jiti, whose require understands TypeScript

	const sidebarModule = require(path);

	return sidebarModule.default ?? sidebarModule;
}

const sidebars: SidebarsConfig = {
	docs: [
		'intro',
		...enabledGroups().map((group) => {
			const reference = group.spec
				? referenceItems(group.dir)
				: group.schema && existsSync(resolve('docs', group.dir, 'reference'))
					? [
							{
								dirName: `${group.dir}/reference`,
								type: 'autogenerated' as const,
							},
						]
					: [];

			return {
				collapsed: false,
				items: [
					`${group.dir}/overview`,
					...(group.schema ? [`${group.dir}/examples`] : []),
					...(reference.length
						? [
								{
									items: reference,
									label: 'Reference',
									type: 'category' as const,
								},
							]
						: []),
				],
				label: group.label,
				type: 'category' as const,
			};
		}),
	],
};

export default sidebars;
