import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';

import {enabledGroups} from './site.config.mjs';

function referenceItems(dir: string) {
	const path = resolve('docs', dir, 'reference', 'sidebar.ts');

	if (!existsSync(path)) {
		return [];
	}

	// Docusaurus loads this file through jiti, whose require understands TypeScript

	const sidebarModule = require(path);

	return sidebarModule.default ?? sidebarModule;
}

const sidebars: SidebarsConfig = {
	docs: [
		'intro',
		...enabledGroups().map((group) => {
			if (group.schema) {
				const queriesDir = `${group.dir}/reference/operations/queries`;

				return {
					collapsed: false,
					items: [
						`${group.dir}/overview`,
						`${group.dir}/examples`,
						...(existsSync(resolve('docs', queriesDir))
							? [
									{
										items: [
											{
												dirName: queriesDir,
												type: 'autogenerated' as const,
											},
										],
										label: 'Queries',
										type: 'category' as const,
									},
								]
							: []),
					],
					label: group.label,
					type: 'category' as const,
				};
			}

			const reference = group.spec ? referenceItems(group.dir) : [];

			return {
				collapsed: false,
				items: [
					`${group.dir}/overview`,
					...(reference.length
						? [
								{
									items: reference,
									label: 'Reference',
									type: 'category' as const,
								},
							]
						: []),
				],
				label: group.label,
				type: 'category' as const,
			};
		}),
	],
};

export default sidebars;
